// <auto-generated />
using System;
using CsCrmApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CsCrmApi.Migrations
{
    [DbContext(typeof(CsCrmDbContext))]
    [Migration("20190825223812_APISetup")]
    partial class APISetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CsCrmApi.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capacity")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("EndDate")
                        .HasMaxLength(20);

                    b.Property<string>("EndTime")
                        .HasMaxLength(20);

                    b.Property<string>("EventType")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasMaxLength(10);

                    b.Property<string>("Location")
                        .HasMaxLength(100);

                    b.Property<string>("Schedule")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("StartDate")
                        .HasMaxLength(20);

                    b.Property<string>("StartTime")
                        .HasMaxLength(20);

                    b.Property<string>("numAttending")
                        .HasMaxLength(20);

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CsCrmApi.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("BirthDate")
                        .HasMaxLength(20);

                    b.Property<string>("City")
                        .HasMaxLength(25);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasMaxLength(25);

                    b.Property<bool>("IsDeleted")
                        .HasMaxLength(10);

                    b.Property<string>("LastName")
                        .HasMaxLength(25);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(15);

                    b.Property<string>("Phone")
                        .HasMaxLength(30);

                    b.Property<string>("SchoolYear")
                        .HasMaxLength(20);

                    b.Property<string>("State")
                        .HasMaxLength(25);

                    b.Property<string>("Status")
                        .HasMaxLength(30);

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20);

                    b.Property<string>("password")
                        .HasMaxLength(25);

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CsCrmApi.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasMaxLength(25);

                    b.Property<bool?>("IsDeleted")
                        .HasMaxLength(10);

                    b.Property<string>("LastName")
                        .HasMaxLength(25);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(15);

                    b.Property<string>("Password")
                        .HasMaxLength(25);

                    b.Property<string>("Phone")
                        .HasMaxLength(30);

                    b.Property<string>("Role")
                        .HasMaxLength(25);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
